table account {
  userId varchar(255) [not null]
  type varchar(255) [not null]
  provider varchar(255) [not null]
  providerAccountId varchar(255) [not null]
  refresh_token varchar(255)
  access_token varchar(255)
  expires_at int
  token_type varchar(255)
  scope varchar(255)
  id_token varchar(2048)
  session_state varchar(255)

  indexes {
    (provider, providerAccountId) [pk]
  }
}

table attachment {
  id varchar(255) [pk, not null]
  course_id varchar(255) [not null]
  name varchar(255) [not null]
  url varchar(255) [not null]
  date timestamp [not null]
}

table authenticator {
  credentialID varchar(255) [not null, unique]
  userId varchar(255) [not null]
  providerAccountId varchar(255) [not null]
  credentialPublicKey varchar(255) [not null]
  counter int [not null]
  credentialDeviceType varchar(255) [not null]
  credentialBackedUp boolean [not null]
  transports varchar(255)

  indexes {
    (userId, credentialID) [pk]
  }
}

table cart {
  user_id varchar(255) [not null]
  course_id varchar(255) [not null]
  created_at timestamp

  indexes {
    (user_id, course_id) [pk]
  }
}

table category {
  id varchar(255) [pk, not null]
  name varchar(255) [not null]
}

table chapter {
  id varchar(255) [pk, not null]
  course_id varchar(255) [not null]
  title varchar(255) [not null]
  description varchar(255)
  position int [not null]
  is_published boolean [default: false]
  is_free boolean [default: false]
}

table comment {
  id varchar(255) [pk, not null]
  user_id varchar(255) [not null]
  course_id varchar(255) [not null]
  content varchar(255)
  created_at timestamp [default: `CURRENT_TIMESTAMP`]
}

table coupon {
  id varchar(255) [pk, not null]
  code varchar(255) [not null, unique]
  discount_type varchar(255) [not null]
  discount_value int [not null]
  expires timestamp
  is_active boolean [not null, default: true]
}

table course {
  id varchar(255) [pk, not null]
  user_id varchar(255) [not null]
  category_id varchar(255)
  level "enum('beginner','intermediate','advanced','all level')" [not null, default: 'all level']
  title varchar(255) [not null]
  description varchar(255)
  image_url varchar(255)
  price int [not null, default: 0]
  is_published boolean [not null, default: false]
  date timestamp [not null]
}

table lesson {
  id varchar(255) [pk, not null]
  chapter_id varchar(255) [not null]
  title varchar(255) [not null]
  description varchar(255)
  lesson_type enum('video','quiz') [not null, default: 'video']
  position int [not null]
  is_published boolean [default: false]
  is_free boolean [default: false]
  video_url varchar(255)
  duration int
  question varchar(255)
  type enum('single_choice','multiple_choice','true_false')
}

table order {
  id varchar(255) [pk, not null]
  user_id varchar(255) [not null]
  payment_id varchar(255) [not null]
  customer_id varchar(255) [not null]
  status varchar(255) [not null]
  created_at timestamp [default: `CURRENT_TIMESTAMP`]
  updated_at timestamp [default: `CURRENT_TIMESTAMP`]
}

table password_reset_token {
  email varchar(255) [not null]
  token varchar(255) [not null, unique]
  expires timestamp [not null]

  indexes {
    (email, token) [pk]
  }
}

table purchases {
  id varchar(255) [pk, not null]
  user_id varchar(255) [not null]
  course_id varchar(255) [not null]
}

table quiz_answer {
  id varchar(255) [pk, not null]
  lesson_id varchar(255) [not null]
  content varchar(255) [not null]
  is_correct boolean [not null]
  explanation varchar(255)
}

table review {
  user_id varchar(255) [not null]
  course_id varchar(255) [not null]
  rating int [not null]
  content varchar(255)
  date timestamp [default: `CURRENT_TIMESTAMP`]

  indexes {
    (user_id, course_id) [pk]
  }
}

table session {
  sessionToken varchar(255) [pk, not null]
  userId varchar(255) [not null]
  expires timestamp [not null]
}

table subscription {
  id varchar(255) [pk, not null]
  user_id varchar(255) [not null]
  subscription_id varchar(255) [not null]
  customer_id varchar(255) [not null]
  price_id varchar(255) [not null]
  status varchar(255) [not null]
  current_period_end timestamp
  created_at timestamp [default: `CURRENT_TIMESTAMP`]
  updated_at timestamp [default: `CURRENT_TIMESTAMP`]
}

table user_lesson_progress {
  id varchar(255) [pk, not null]
  user_id varchar(255) [not null]
  lesson_id varchar(255) [not null]
  is_completed boolean [default: false]
  date timestamp [default: `CURRENT_TIMESTAMP`]
}

table user {
  id varchar(255) [pk, not null]
  name varchar(255)
  email varchar(255) [unique]
  emailVerified timestamp(3)
  role enum('admin','user') [not null, default: 'user']
  image varchar(255)
  password varchar(255)
}

table verification_token {
  email varchar(255) [not null]
  token varchar(255) [not null]
  expires timestamp [not null]

  indexes {
    (email, token) [pk]
  }
}

table wishlist {
  user_id varchar(255) [not null]
  course_id varchar(255) [not null]
  date timestamp [default: `CURRENT_TIMESTAMP`]

  indexes {
    (user_id, course_id) [pk]
  }
}

ref: attachment.course_id > course.id

ref: chapter.course_id > course.id

ref: course.category_id - category.id

ref: course.user_id - user.id

ref: lesson.chapter_id > chapter.id

ref: purchases.course_id > course.id