table account {
  userId text [not null]
  type text [not null]
  provider text [not null]
  providerAccountId text [not null]
  refresh_token text
  access_token text
  expires_at integer
  token_type text
  scope text
  id_token text
  session_state text

  indexes {
    (provider, providerAccountId) [pk]
  }
}

table attachment {
  id text [pk, not null]
  course_id text [not null]
  name text [not null]
  url text [not null]
  date timestamp [not null]
}

table authenticator {
  credentialID text [not null, unique]
  userId text [not null]
  providerAccountId text [not null]
  credentialPublicKey text [not null]
  counter integer [not null]
  credentialDeviceType text [not null]
  credentialBackedUp boolean [not null]
  transports text

  indexes {
    (userId, credentialID) [pk]
  }
}

table category {
  id text [pk, not null]
  name text [not null]
}

table chapter {
  id text [pk, not null]
  course_id text [not null]
  title text [not null]
  description text
  video_url text
  position integer [not null]
  is_published boolean [default: false]
  is_free boolean [default: false]
}

table course {
  id text [pk, not null]
  teacher_id text [not null]
  category_id text
  title text [not null]
  description text
  image_url text
  price integer [not null, default: 0]
  is_published boolean [not null, default: false]
  date timestamp [not null]
}

table mux_data {
  id text [pk, not null]
  chapter_id text [not null]
  asset_id text [not null]
  playback_id text
}

table order_detail {
  id text [pk, not null]
  order_id text [not null]
  course_id text [not null]
  quantity integer [not null]
  price integer [not null]
}

table order {
  id text [pk, not null]
  userId text [not null]
  total_amount integer [not null]
  createdAt timestamp [not null]
  updatedAt timestamp [not null]
}

table password_reset_token {
  email text [not null]
  token text [not null, unique]
  expires timestamp [not null]

  indexes {
    (email, token) [pk]
  }
}

table purchases {
  id text [pk, not null]
  userId text [not null]
  course_id text [not null]
}

table review {
  id text [pk, not null]
  userId text [not null]
  course_id text [not null]
  rating integer [not null]
  comment text
  createdAt timestamp [not null]
}

table role {
  id text [pk, not null]
  name text [not null, unique]
}

table session {
  sessionToken text [pk, not null]
  userId text [not null]
  expires timestamp [not null]
}

table subscription {
  id text [pk, not null]
  userId text [not null]
  subscriptionId text [not null]
  customerId text [not null]
  priceId text [not null]
  status text [not null]
  currentPeriodEnd timestamp
  createdAt timestamp [not null]
  updatedAt timestamp [not null]
}

table teacher {
  id text [pk, not null]
  userId text [not null]
}

table user_progress {
  id text [pk, not null]
  userId text [not null]
  chapter_id text [not null]
  is_completed boolean [default: false]
}

table user {
  id text [pk, not null]
  name text
  email text [not null]
  emailVerified timestamp
  image text
  password text
}

table verification_token {
  email text [not null]
  token text [not null, unique]
  expires timestamp [not null]

  indexes {
    (email, token) [pk]
  }
}

ref: attachment.course_id > course.id

ref: chapter.course_id > course.id

ref: mux_data.chapter_id - chapter.id

ref: course.category_id - category.id

ref: course.teacher_id - teacher.id

ref: order_detail.order_id > order.id

ref: order_detail.course_id - course.id

ref: purchases.course_id > course.id

ref: user_progress.chapter_id > chapter.id