import { CourseLevel } from '@/db/schema'
import { v4 as uuidv4 } from 'uuid'

import { SEED_CATEGORIES } from './categories'

const userId = '349866a8-e523-48e6-94a9-d8ce8a550a59'

export const SEED_COURSES = [
  {
    id: uuidv4(),
    title: 'React TypeScript Tutorial',
    desc: 'React TypeScript Tutorial for Beginners Introduction',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/TiSGujM22OI/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAZaoCQQ_WDeCzeimnEpif-qah-2g',
    price: 20,
    isPublished: true,
    level: CourseLevel.ALL_LEVEL,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Next.js 13 Crash Course',
    desc: 'Next.js 13 Crash Course',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/TJQbDPGzm0Y/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCmQt8pp9F4sofRDy_t2-lNSKosEg',
    price: 7,
    isPublished: true,
    level: CourseLevel.INTERMEDIATE,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Next.js Tutorial - Beginner to Advanced',
    desc: 'Next.js Tutorial - Beginner to Advanced',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/ZjAqacIC_3c/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCFrkxkw_AUBpKpLPESu8U6OleRlw',
    price: 12,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Redis for Beginners',
    desc: 'Redis for Beginners',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/8sHCdz_tOjk/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCaE9iL3F83rCNxoXeEt_4Ig1dF5w',
    price: 2,
    isPublished: true,
    level: CourseLevel.ALL_LEVEL,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Python Crash Course',
    desc: 'Python Crash Course',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/wdp7smAtqZI/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAR6kk-LpgazA2jz8ZwBwYs99_K5Q',
    price: 12,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Complete Django Tutorial',
    desc: 'Complete Django Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/ZpKl3U-arN8/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDgFtN7AcQlhKitpAVCNLlBA4mw5Q',
    price: 3,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Shadcn UI Tutorial',
    desc: 'Shadcn UI Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/wcTzlJi2Oz4/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDt-09Ko5uG-7e-qe58eMvMGFjzZA',
    price: 12,
    isPublished: true,
    level: CourseLevel.BEGINNER,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Chakra UI Tutorial',
    desc: 'Chakra UI Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/iXsM6NkEmFc/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCt0AzVoUsWtlSz7vQu0voye8b7fw',
    price: 1,
    isPublished: true,
    level: CourseLevel.BEGINNER,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'GraphQL Crash Course',
    desc: 'GraphQL Crash Course',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/xMCnDesBggM/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDuXOGMuMKAHRjt5SvYVaS6JnLX2w',
    price: 4,
    isPublished: true,
    level: CourseLevel.INTERMEDIATE,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Flutter Crash Course',
    desc: 'Flutter Crash Course',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/j_rCDc_X-k8/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDq5ApclBMJkKX-BiiqP2mxkNDnXA',
    price: 8,
    isPublished: true,
    level: CourseLevel.ALL_LEVEL,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Dart Crash Course',
    desc: 'Dart Crash Course',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/QGqMJzywasg/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC-nbnCl8HBwMp6hzy0jqAvp-M-Dw',
    price: 7,
    isPublished: true,
    level: CourseLevel.INTERMEDIATE,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Node.js Tutorial',
    desc: 'Node.js Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/LAUi8pPlcUM/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLANsMIsCM_ymftUEiye-G0nswiaWQ',
    price: 2,
    isPublished: true,
    level: CourseLevel.INTERMEDIATE,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'JavaScript Algorithms',
    desc: 'JavaScript Algorithms',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/coqQwbDezUA/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLACUdflCaZWmlVFOrQrMmsX5zxpJA',
    price: 4,
    isPublished: true,
    level: CourseLevel.INTERMEDIATE,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Redux Toolkit Tutorial',
    desc: 'Redux Toolkit Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/0awA5Uw6SJE/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCXUfi_JwruX6gE4Y2xmoqhxzBVnA',
    price: 5,
    isPublished: true,
    level: CourseLevel.BEGINNER,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Angular Tutorial For Beginners',
    desc: 'Angular Tutorial For Beginners',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/0eWrpsCLMJQ/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB_bQXTa4Q4KUl1rT8LngUlHBQoow',
    price: 2,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Tanstack Query v5',
    desc: 'Tanstack Query v5',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/zzgrHUn4kb4/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB8sTf4xEstnfIYX4Kz0rtZCxOzEQ',
    price: 1,
    isPublished: true,
    level: CourseLevel.ALL_LEVEL,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Typescript for beginners',
    desc: 'Typescript for beginners',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/_yfpSc6ubLE/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCllipkhH2f54dDW6QOv8vAl5YBow',
    price: 2,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Javascript Data Structures',
    desc: 'Javascript Data Structures',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/_yfpSc6ubLE/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCllipkhH2f54dDW6QOv8vAl5YBow',
    price: 3,
    isPublished: true,
    level: CourseLevel.ALL_LEVEL,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'React Testing Tutorial',
    desc: 'React Testing Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/T2sv8jXoP4s/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCxlABk6e17HXjqN2-sZ3bLqh4uqQ',
    price: 1,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Supabase Crash Course',
    desc: 'Supabase Crash Course',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/ydz7Dj5QHKY/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCHLnBB3sNcs0tEcFZt9BOXOJLK6Q',
    price: 2,
    isPublished: true,
    level: CourseLevel.ALL_LEVEL,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Firebase 9 Tutorial',
    desc: 'Firebase 9 Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/9zdvmgGsww0/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBqZKXHC7mBRl2f_FoRYtn_bWljkQ',
    price: 4,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Stripe Tutorial (with React & GraphQL)',
    desc: 'Stripe Tutorial (with React & GraphQL)',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/4Ntd414raYc/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB6DHRMuO2yNzbk1HrIrm6bEhuw7Q',
    price: 8,
    isPublished: true,
    level: CourseLevel.INTERMEDIATE,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Docker Crash Course Tutorial',
    desc: 'Docker Crash Course Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/31ieHmcTUOk/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCVasS1zV1njrPhehcto-5tTMMK7g',
    price: 2,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Nuxt 3 Tutorial',
    desc: 'Nuxt 3 Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/GBdO5myZNsQ/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLANM0Pw2FckfcEDwrPRrp2aEuPIzA',
    price: 3,
    isPublished: true,
    level: CourseLevel.ALL_LEVEL,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Node.js Auth Tutorial (JWT)',
    desc: 'Node.js Auth Tutorial (JWT)',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/SnoAwLP1a-0/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLADRYbjQYppGEy4yvfNnEahhe7IUw',
    price: 3,
    isPublished: true,
    level: CourseLevel.INTERMEDIATE,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Go tutorial (Golang) for Beginners',
    desc: 'Go tutorial (Golang) for Beginners',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/etSN4X_fCnM/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCrticKKYhWCPH_Ul31OkB8E4fBgw',
    price: 2,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Nuxt & Pinia with Firestore Tutorial',
    desc: 'Nuxt & Pinia with Firestore Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/nm069pZBFTg/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBw6pOkzpIseFkAdcii-IvbvLlEkA',
    price: 5,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
]
