import { CourseLevel } from '@/db/schema'
import { v4 as uuidv4 } from 'uuid'

import { SEED_CATEGORIES } from './categories'
import { SEED_USERS } from './users'

const userId = SEED_USERS[0].id

export const SEED_COURSES = [
  {
    id: uuidv4(),
    title: 'React TypeScript Tutorial',
    desc: 'React TypeScript Tutorial for Beginners Introduction',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/TiSGujM22OI/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAZaoCQQ_WDeCzeimnEpif-qah-2g',
    price: 20,
    isPublished: true,
    level: CourseLevel.ALL_LEVEL,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Next.js 13 Crash Course',
    desc: 'Next.js 13 Crash Course',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/TJQbDPGzm0Y/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCmQt8pp9F4sofRDy_t2-lNSKosEg',
    price: 7,
    isPublished: true,
    level: CourseLevel.INTERMEDIATE,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Next.js Tutorial - Beginner to Advanced',
    desc: 'Next.js Tutorial - Beginner to Advanced',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/ZjAqacIC_3c/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCFrkxkw_AUBpKpLPESu8U6OleRlw',
    price: 12,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Redis for Beginners',
    desc: 'Redis for Beginners',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/8sHCdz_tOjk/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCaE9iL3F83rCNxoXeEt_4Ig1dF5w',
    price: 2,
    isPublished: true,
    level: CourseLevel.ALL_LEVEL,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Python Crash Course',
    desc: 'Python Crash Course',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/wdp7smAtqZI/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAR6kk-LpgazA2jz8ZwBwYs99_K5Q',
    price: 12,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Complete Django Tutorial',
    desc: 'Complete Django Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/ZpKl3U-arN8/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDgFtN7AcQlhKitpAVCNLlBA4mw5Q',
    price: 3,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Shadcn UI Tutorial',
    desc: 'Shadcn UI Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/wcTzlJi2Oz4/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDt-09Ko5uG-7e-qe58eMvMGFjzZA',
    price: 12,
    isPublished: true,
    level: CourseLevel.BEGINNER,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Chakra UI Tutorial',
    desc: 'Chakra UI Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/iXsM6NkEmFc/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCt0AzVoUsWtlSz7vQu0voye8b7fw',
    price: 1,
    isPublished: true,
    level: CourseLevel.BEGINNER,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'GraphQL Crash Course',
    desc: 'GraphQL Crash Course',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/xMCnDesBggM/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDuXOGMuMKAHRjt5SvYVaS6JnLX2w',
    price: 4,
    isPublished: true,
    level: CourseLevel.INTERMEDIATE,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Flutter Crash Course',
    desc: 'Flutter Crash Course',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/j_rCDc_X-k8/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDq5ApclBMJkKX-BiiqP2mxkNDnXA',
    price: 8,
    isPublished: true,
    level: CourseLevel.ALL_LEVEL,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Dart Crash Course',
    desc: 'Dart Crash Course',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/QGqMJzywasg/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC-nbnCl8HBwMp6hzy0jqAvp-M-Dw',
    price: 7,
    isPublished: true,
    level: CourseLevel.INTERMEDIATE,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Node.js Tutorial',
    desc: 'Node.js Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/LAUi8pPlcUM/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLANsMIsCM_ymftUEiye-G0nswiaWQ',
    price: 2,
    isPublished: true,
    level: CourseLevel.INTERMEDIATE,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'JavaScript Algorithms',
    desc: 'JavaScript Algorithms',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/coqQwbDezUA/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLACUdflCaZWmlVFOrQrMmsX5zxpJA',
    price: 4,
    isPublished: true,
    level: CourseLevel.INTERMEDIATE,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Redux Toolkit Tutorial',
    desc: 'Redux Toolkit Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/0awA5Uw6SJE/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCXUfi_JwruX6gE4Y2xmoqhxzBVnA',
    price: 5,
    isPublished: true,
    level: CourseLevel.BEGINNER,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Angular Tutorial For Beginners',
    desc: 'Angular Tutorial For Beginners',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/0eWrpsCLMJQ/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB_bQXTa4Q4KUl1rT8LngUlHBQoow',
    price: 2,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Tanstack Query v5',
    desc: 'Tanstack Query v5',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/zzgrHUn4kb4/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB8sTf4xEstnfIYX4Kz0rtZCxOzEQ',
    price: 1,
    isPublished: true,
    level: CourseLevel.ALL_LEVEL,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Typescript for beginners',
    desc: 'Typescript for beginners',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/_yfpSc6ubLE/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCllipkhH2f54dDW6QOv8vAl5YBow',
    price: 2,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Javascript Data Structures',
    desc: 'Javascript Data Structures',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/_yfpSc6ubLE/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCllipkhH2f54dDW6QOv8vAl5YBow',
    price: 3,
    isPublished: true,
    level: CourseLevel.ALL_LEVEL,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'React Testing Tutorial',
    desc: 'React Testing Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/T2sv8jXoP4s/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCxlABk6e17HXjqN2-sZ3bLqh4uqQ',
    price: 1,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Supabase Crash Course',
    desc: 'Supabase Crash Course',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/ydz7Dj5QHKY/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCHLnBB3sNcs0tEcFZt9BOXOJLK6Q',
    price: 2,
    isPublished: true,
    level: CourseLevel.ALL_LEVEL,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Firebase 9 Tutorial',
    desc: 'Firebase 9 Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/9zdvmgGsww0/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBqZKXHC7mBRl2f_FoRYtn_bWljkQ',
    price: 4,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Stripe Tutorial (with React & GraphQL)',
    desc: 'Stripe Tutorial (with React & GraphQL)',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/4Ntd414raYc/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB6DHRMuO2yNzbk1HrIrm6bEhuw7Q',
    price: 8,
    isPublished: true,
    level: CourseLevel.INTERMEDIATE,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Docker Crash Course Tutorial',
    desc: 'Docker Crash Course Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/31ieHmcTUOk/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCVasS1zV1njrPhehcto-5tTMMK7g',
    price: 2,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Nuxt 3 Tutorial',
    desc: 'Nuxt 3 Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/GBdO5myZNsQ/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLANM0Pw2FckfcEDwrPRrp2aEuPIzA',
    price: 3,
    isPublished: true,
    level: CourseLevel.ALL_LEVEL,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Node.js Auth Tutorial (JWT)',
    desc: 'Node.js Auth Tutorial (JWT)',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/SnoAwLP1a-0/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLADRYbjQYppGEy4yvfNnEahhe7IUw',
    price: 3,
    isPublished: true,
    level: CourseLevel.INTERMEDIATE,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Go tutorial (Golang) for Beginners',
    desc: 'Go tutorial (Golang) for Beginners',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/etSN4X_fCnM/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCrticKKYhWCPH_Ul31OkB8E4fBgw',
    price: 2,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Nuxt & Pinia with Firestore Tutorial',
    desc: 'Nuxt & Pinia with Firestore Tutorial',
    userId,
    categoryId: SEED_CATEGORIES[0].id,
    imageUrl:
      'https://i.ytimg.com/vi/nm069pZBFTg/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBw6pOkzpIseFkAdcii-IvbvLlEkA',
    price: 5,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Personality Development',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
    userId,
    categoryId: SEED_CATEGORIES[6].id,
    imageUrl:
      'https://i.ytimg.com/vi/v2euEwGnas8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB5jk26z8IsP8YO3B1PfPB4J4fJDA',
    price: 100,
    isPublished: true,
    level: CourseLevel.BEGINNER,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Best Personal Development Course',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
    userId,
    categoryId: SEED_CATEGORIES[6].id,
    imageUrl:
      'https://i.ytimg.com/vi/d479F8VuaJA/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBP8pUnUtG-OWALRkpz3y5cVjC49w',
    price: 50,
    isPublished: true,
    level: CourseLevel.BEGINNER,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Personality Development Training Course',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
    userId,
    categoryId: SEED_CATEGORIES[6].id,
    imageUrl:
      'https://i.ytimg.com/vi/cDHGpfpw9kY/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCgXTCEM6YwaHZHStXgpQFzT9LZxA',
    price: 60,
    isPublished: true,
    level: CourseLevel.BEGINNER,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'How to Perfect Your Sales Process and Increase Sales FAST!',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
    userId,
    categoryId: SEED_CATEGORIES[7].id,
    imageUrl:
      'https://i.ytimg.com/vi/3eM4psQQiQ4/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC5o-AbyG_THfcDA5oJSIV-5he2hQ',
    price: 130,
    isPublished: true,
    level: CourseLevel.BEGINNER,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: '10 Steps That’ll Turn You Into A Sales Machine',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
    userId,
    categoryId: SEED_CATEGORIES[7].id,
    imageUrl:
      'https://i.ytimg.com/vi/amdXa3CfzHw/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBpNw7-ozILLWIYandkJC19OTHF5g',
    price: 70,
    isPublished: true,
    level: CourseLevel.BEGINNER,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Civil Engineering: Crash Course Engineering',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
    userId,
    categoryId: SEED_CATEGORIES[8].id,
    imageUrl:
      'https://i.ytimg.com/vi/-xbtnz4wdaA/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBs2zY69ptEXO8uibzdcepjCDxKiw',
    price: 40,
    isPublished: true,
    level: CourseLevel.BEGINNER,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Beginner English Introduction',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
    userId,
    categoryId: SEED_CATEGORIES[5].id,
    imageUrl:
      'https://i.ytimg.com/vi/CbPy_CjJR90/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBuQAP2pv46R-eBU12G0Db60ONvaw',
    price: 20,
    isPublished: true,
    level: CourseLevel.BEGINNER,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'How to Learn English On Your Own',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
    userId,
    categoryId: SEED_CATEGORIES[5].id,
    imageUrl:
      'https://i.ytimg.com/vi/tLULIzOj-Ew/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDuwlTQ7jLKqTc-tV5xM1kw2pRiHA',
    price: 10,
    isPublished: true,
    level: CourseLevel.BEGINNER,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: '60 Days Spoken English Course',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
    userId,
    categoryId: SEED_CATEGORIES[5].id,
    imageUrl:
      'https://i.ytimg.com/vi/OnSUWIyQqIc/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCkO4Ow7ld6Uq36qmwwdMfa8midEA',
    price: 15,
    isPublished: true,
    level: CourseLevel.BEGINNER,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'English for Beginners: Learn English Online',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
    userId,
    categoryId: SEED_CATEGORIES[5].id,
    imageUrl:
      'https://i.ytimg.com/vi/xTLK0iHLxFs/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBmkunaAoS4hTH5YJx8qpk0SICQ1w',
    price: 22,
    isPublished: true,
    level: CourseLevel.BEGINNER,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'English Course - Beginner 2',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
    userId,
    categoryId: SEED_CATEGORIES[5].id,
    imageUrl:
      'https://i.ytimg.com/vi/qKdtyu5NTPA/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBMa5XfWCX0bRBrLlb3PdecJ3g8GQ',
    price: 12,
    isPublished: true,
    level: CourseLevel.BEGINNER,
    date: new Date(),
  },
  //Hào
  {
    id: uuidv4(),
    title: 'Your Ultimate Health Playlist: Empowering Wellness and Vitalityl',
    desc: 'Your Ultimate Health Playlist: Empowering Wellness and Vitality',
    userId,
    categoryId: SEED_CATEGORIES[1].id,
    imageUrl:
      'https://i.ytimg.com/vi/cfpITyzu-Ys/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD4fpjQljZx-RKVLR6BXAp6rjQhLQA',
    price: 100,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'ULTIMATE HEALTH PLAYLIST! Fitness, Nutrition, Mental Health',
    desc: 'ULTIMATE HEALTH PLAYLIST! Fitness, Nutrition, Mental Health',
    userId,
    categoryId: SEED_CATEGORIES[1].id,
    imageUrl:
      'https://i.ytimg.com/vi/i7Xlvd4J_G8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBVPEklfwSqWDC6SOxLWstSt0f_Cw',
    price: 150,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Most Popular Health Videos',
    desc: 'Most Popular Health Videos',
    userId,
    categoryId: SEED_CATEGORIES[1].id,
    imageUrl:
      'https://i.ytimg.com/vi/F7gDIshc-S0/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBEcOkVlMH6PIOB4Vu2B47ksxW4YA',
    price: 80,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Physical Health',
    desc: 'Physical Health',
    userId,
    categoryId: SEED_CATEGORIES[1].id,
    imageUrl:
      'https://i.ytimg.com/vi/8ZIqsKCq_tw/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAIAP2xyo_L_Gv6AWWRCBxG2MHacw',
    price: 120,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Gentle Strength Training (Level 1)',
    desc: 'Gentle Strength Training (Level 1)',
    userId,
    categoryId: SEED_CATEGORIES[1].id,
    imageUrl:
      'https://i.ytimg.com/vi/_0vtnVMd26E/hqdefault.jpg?sqp=-oaymwEpCNACELwBSFryq4qpAxsIARUAAIhCGAHYAQHiAQwIHBACGAYgATgBQAE=&rs=AOn4CLCWPKmlOiQTRKJFua2ZGd7z8fxs4Q',
    price: 50,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Beginner Strength Training (Level 2)',
    desc: 'Beginner Strength Training (Level 2)',
    userId,
    categoryId: SEED_CATEGORIES[1].id,
    imageUrl:
      'https://i.ytimg.com/vi/2qI3RwOZfsY/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBFMEF2fMu3LNCBPVl5slpO2ZWvWA',
    price: 120,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'GENERAL HEALTH',
    desc: 'GENERAL HEALTH',
    userId,
    categoryId: SEED_CATEGORIES[1].id,
    imageUrl:
      'https://i.ytimg.com/vi/wZU_3xFdPS4/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCGJk6fsAHoytJA1rTRcLNQ41izaw',
    price: 80,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Ask HIV: Provider to Provider',
    desc: 'Ask HIV: Provider to Provider',
    userId,
    categoryId: SEED_CATEGORIES[1].id,
    imageUrl:
      'https://i.ytimg.com/vi/ND__mOG6czA/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBG5fSKg9F5Fv-3j0YDn6f-DWkMRA',
    price: 130,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'The Ultimate Health and Fitness Playlist',
    desc: 'The Ultimate Health and Fitness Playlist',
    userId,
    categoryId: SEED_CATEGORIES[1].id,
    imageUrl:
      'https://i.ytimg.com/vi/jrVd4-PpUuY/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBYWjVQkHN-HAIpaP3ySID-5XbBdw',
    price: 90,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Self-Care Videos',
    desc: 'Self-Care Videos',
    userId,
    categoryId: SEED_CATEGORIES[1].id,
    imageUrl:
      'https://i.ytimg.com/vi/-eGQ5RyKGZE/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBlpes8MB8VayVqAFCDyNZZgtdsFQ',
    price: 70,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Self Care Tips & Routines',
    desc: 'Self Care Tips & Routines',
    userId,
    categoryId: SEED_CATEGORIES[1].id,
    imageUrl:
      'https://i.ytimg.com/vi/CHaeoyfti-w/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDpDzVfsUCwYY65qvk9Q308TsxWTw',
    price: 100,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Nutrition and Exercise',
    desc: 'Nutrition and Exercise',
    userId,
    categoryId: SEED_CATEGORIES[1].id,
    imageUrl:
      'https://i.ytimg.com/vi/AuDbvBlDer4/hqdefault.jpg?sqp=-oaymwExCNACELwBSFryq4qpAyMIARUAAIhCGAHwAQH4AdQGgALgA4oCDAgAEAEYZSBlKGUwDw==&rs=AOn4CLCi4Eyq0gpIiIecXrR70UxNECg3JA',
    price: 130,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'English Vocabulary Lessons',
    desc: 'English Vocabulary Lessons',
    userId,
    categoryId: SEED_CATEGORIES[2].id,
    imageUrl:
      'https://i.ytimg.com/vi/hoyhPZDp3dE/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBPkKZ7L61RAUcPo31sTl-XhK90VA',
    price: 100,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'English Grammar Lessons',
    desc: 'English Grammar Lessons',
    userId,
    categoryId: SEED_CATEGORIES[2].id,
    imageUrl:
      'https://i.ytimg.com/vi/jul2urONzOQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCI---XL9pvMdpKsaKGj7Up49q_Cg',
    price: 150,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Learn Basic Spanish Vocabulary',
    desc: 'Learn Basic Spanish Vocabulary',
    userId,
    categoryId: SEED_CATEGORIES[2].id,
    imageUrl:
      'https://i.ytimg.com/vi/KrRsGsOt-EM/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAlwmiX5njIwpzIlfTk_pljMn6wCQ',
    price: 80,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Innovative Language',
    desc: 'Innovative Language',
    userId,
    categoryId: SEED_CATEGORIES[2].id,
    imageUrl:
      'https://i.ytimg.com/vi/bex2D4yX6cA/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBQpZZgI49uUmm9CFgXn2hoyk-SZg',
    price: 120,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Learn spanish - Learn With Video',
    desc: 'Learn spanish - Learn With Video',
    userId,
    categoryId: SEED_CATEGORIES[2].id,
    imageUrl:
      'https://i.ytimg.com/vi/T8_4KHuMm00/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDNB-Dnf8IfExsyvANtOJw0XDPtDg',
    price: 50,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Basic French Vocabulary',
    desc: 'Basic French Vocabulary',
    userId,
    categoryId: SEED_CATEGORIES[2].id,
    imageUrl:
      'https://i.ytimg.com/vi/dPRBkFpl6IA/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBy05w8hhxVkS8HNC_hx0aEc7LOew',
    price: 120,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Common French Verbs',
    desc: 'Common French Verbs',
    userId,
    categoryId: SEED_CATEGORIES[2].id,
    imageUrl:
      'https://i.ytimg.com/vi/sA82J16mNfU/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC4XYlhIkyMle-AiIbkUSTzYczjpQ',
    price: 80,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Free full lessons',
    desc: 'Free full lessons',
    userId,
    categoryId: SEED_CATEGORIES[2].id,
    imageUrl:
      'https://i.ytimg.com/vi/YhXYEEDFCsg/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCSjbBvf5n7tsz0aJkUOf8EZ8C9yA',
    price: 130,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Learn the Most Common Chinese Characters 1 - 300',
    desc: 'Learn the Most Common Chinese Characters 1 - 300',
    userId,
    categoryId: SEED_CATEGORIES[2].id,
    imageUrl:
      'https://i.ytimg.com/vi/pCqnrMlyBIY/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBHyURhY-YbCmP72ENskmVu1XepzQ',
    price: 90,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Learn the Most Common Chinese Characters 301-600',
    desc: 'Learn the Most Common Chinese Characters 301-600',
    userId,
    categoryId: SEED_CATEGORIES[2].id,
    imageUrl:
      'https://i.ytimg.com/vi/-eGQ5RyKGZE/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBlpes8MB8VayVqAFCDyNZZgtdsFQ',
    price: 70,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Learn Beginner Chinese: Phrase of the Day Series',
    desc: 'Learn Beginner Chinese: Phrase of the Day Series',
    userId,
    categoryId: SEED_CATEGORIES[2].id,
    imageUrl:
      'https://i.ytimg.com/vi/YjRAxl2RrHI/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCAfHM4I5liHOhGUZaA5K52rPTarg',
    price: 100,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Japanese Vocabulary - Learn Japanese Words and Phrases',
    desc: 'Japanese Vocabulary - Learn Japanese Words and Phrases',
    userId,
    categoryId: SEED_CATEGORIES[2].id,
    imageUrl:
      'https://i.ytimg.com/vi/Mz3uCFOStt4/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBf8KFR9DZTOLm95RHFKROEKaOf6w',
    price: 130,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Business Analyst Training Videos',
    desc: 'Business Analyst Training Videos',
    userId,
    categoryId: SEED_CATEGORIES[3].id,
    imageUrl:
      'https://i.ytimg.com/vi/f9DzS6NdgwU/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDcC35c-Al-sTxzVdrwYJlptbLv1w',
    price: 100,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Business And Management',
    desc: 'Business And Management',
    userId,
    categoryId: SEED_CATEGORIES[3].id,
    imageUrl:
      'https://i.ytimg.com/vi/NjOa6l4GFJA/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBDgyIZpsMPkkv6THW1pJcYMZT_ug',
    price: 150,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Business Analyst Tutorials',
    desc: 'Business Analyst Tutorials',
    userId,
    categoryId: SEED_CATEGORIES[3].id,
    imageUrl:
      'https://i.ytimg.com/vi/pDpXn5bgMDM/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLA-doeCBVdHHDFkxNjEB4GLsAgGAw',
    price: 80,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Business Entrepreneurship',
    desc: 'Business Entrepreneurship',
    userId,
    categoryId: SEED_CATEGORIES[3].id,
    imageUrl:
      'https://i.ytimg.com/vi/YHBVjv4MYXE/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC08Pb3Ya1KTZdGa6Wjo_9n42iuXA',
    price: 120,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Business Management Course 101',
    desc: 'Business Management Course 101',
    userId,
    categoryId: SEED_CATEGORIES[3].id,
    imageUrl:
      'https://i.ytimg.com/vi/T3l51Psce3c/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCW0nkF-xEeJJqu5vTOa0uCL2q2_w',
    price: 50,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Small Business Marketing 101 Course',
    desc: 'Small Business Marketing 101 Course',
    userId,
    categoryId: SEED_CATEGORIES[3].id,
    imageUrl:
      'https://i.ytimg.com/vi/IIE-bbp2Ios/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBnYE0y4YyF9ZYXsdbwLFIKv5HVtA',
    price: 120,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'How to Write a Business Plan Full Course',
    desc: 'How to Write a Business Plan Full Course',
    userId,
    categoryId: SEED_CATEGORIES[3].id,
    imageUrl:
      'https://i.ytimg.com/vi/u76jqbqgbmc/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB1ddSXckzwpAeFp_2Oxer9loLQcw',
    price: 80,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Business Strategy A-Z Course ',
    desc: 'Business Strategy A-Z Course ',
    userId,
    categoryId: SEED_CATEGORIES[3].id,
    imageUrl:
      'https://i.ytimg.com/vi/bLvNaSTcX9o/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCXJIXAngEUSaiLvvdojxudVaif6A',
    price: 130,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Master of Business Administration',
    desc: 'Master of Business Administration',
    userId,
    categoryId: SEED_CATEGORIES[3].id,
    imageUrl:
      'https://i.ytimg.com/vi/EVkg38OOtZs/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLADWTr_xOXywKvWpjA1U47YTN18SQ',
    price: 90,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Start an Online Business',
    desc: 'Start an Online Business',
    userId,
    categoryId: SEED_CATEGORIES[3].id,
    imageUrl:
      'https://i.ytimg.com/vi/JT00xhBosjY/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDAm3s4CIUL4S894-rFG_GYOdRnhg',
    price: 70,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Small Business Education for Beginners',
    desc: 'Small Business Education for Beginners',
    userId,
    categoryId: SEED_CATEGORIES[3].id,
    imageUrl:
      'https://i.ytimg.com/vi/ydau_q9OJVA/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCd-43vrbGHY3bRfYgbbzvNIBWumw',
    price: 100,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'How to Start a Business With No Money - Free Business Course',
    desc: 'How to Start a Business With No Money - Free Business Course',
    userId,
    categoryId: SEED_CATEGORIES[3].id,
    imageUrl:
      'https://i.ytimg.com/vi/FvaQHgQ6-0Y/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAVGwcM7NVcYvBW1HwaFUbw3YEUOA',
    price: 130,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Principles of Management',
    desc: 'Principles of Management',
    userId,
    categoryId: SEED_CATEGORIES[4].id,
    imageUrl:
      'https://i.ytimg.com/vi/JH4srpPMgAc/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAoTUBpnQiwpIzKyvJmt4l7KUY2oQ',
    price: 70,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Principles of Management',
    desc: 'Principles of Management',
    userId,
    categoryId: SEED_CATEGORIES[4].id,
    imageUrl:
      'https://i.ytimg.com/vi/vOykcERGw9Y/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD4xfmZon4IVaML-7JGPUxx4pHtxg',
    price: 90,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Management Principles and Practices',
    desc: 'Management Principles and Practices',
    userId,
    categoryId: SEED_CATEGORIES[4].id,
    imageUrl:
      'https://i.ytimg.com/vi/K1GlTGZOBeM/hqdefault.jpg?sqp=-oaymwExCNACELwBSFryq4qpAyMIARUAAIhCGAHwAQH4Af4JgALQBYoCDAgAEAEYNyBMKH8wDw==&rs=AOn4CLD77FfnQyrTFun-hajg0dEUnCo28A',
    price: 50,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'MBA Lectures - Principles of Marketing',
    desc: 'MBA Lectures - Principles of Marketing',
    userId,
    categoryId: SEED_CATEGORIES[4].id,
    imageUrl:
      'https://i.ytimg.com/vi/6jobOJy96jM/hqdefault.jpg?sqp=-oaymwExCNACELwBSFryq4qpAyMIARUAAIhCGAHwAQH4AdQGgALgA4oCDAgAEAEYZSBlKGUwDw==&rs=AOn4CLDvgCdvPecU1BEoCtDEMihEpCYe9g',
    price: 120,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Google Project Management Certificate',
    desc: 'Google Project Management Certificate',
    userId,
    categoryId: SEED_CATEGORIES[4].id,
    imageUrl:
      'https://i.ytimg.com/vi/rck3MnC7OXA/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAo7_uGHHIfMR3VuBFovWKhuZ1GyQ',
    price: 100,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Principle of Management playlist',
    desc: 'Principle of Management playlist',
    userId,
    categoryId: SEED_CATEGORIES[4].id,
    imageUrl:
      'https://i.ytimg.com/vi/eH6VgHs5mwU/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD29CWeEPwyKIleET3j9jINhbx8YA',
    price: 60,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Delhi University Bcom (Hons) Sem 1 MPP ',
    desc: 'Delhi University Bcom (Hons) Sem 1 MPP ',
    userId,
    categoryId: SEED_CATEGORIES[4].id,
    imageUrl:
      'https://i.ytimg.com/vi/K1GlTGZOBeM/hqdefault.jpg?sqp=-oaymwExCNACELwBSFryq4qpAyMIARUAAIhCGAHwAQH4Af4JgALQBYoCDAgAEAEYNyBMKH8wDw==&rs=AOn4CLD77FfnQyrTFun-hajg0dEUnCo28A',
    price: 90,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'IRDAI Grade A exam preparation Management Complete Syllabus',
    desc: 'IRDAI Grade A exam preparation Management Complete Syllabus',
    userId,
    categoryId: SEED_CATEGORIES[4].id,
    imageUrl:
      'https://i.ytimg.com/vi/K1GlTGZOBeM/hqdefault.jpg?sqp=-oaymwExCNACELwBSFryq4qpAyMIARUAAIhCGAHwAQH4Af4JgALQBYoCDAgAEAEYNyBMKH8wDw==&rs=AOn4CLD77FfnQyrTFun-hajg0dEUnCo28A',
    price: 110,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Financial Management',
    desc: 'Financial Management',
    userId,
    categoryId: SEED_CATEGORIES[4].id,
    imageUrl:
      'https://i.ytimg.com/vi/wkXP8_MWcbQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAalwVvZLjAZ1tvic7_onTv7Tp4fQ',
    price: 50,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Principles of Management',
    desc: 'Principles of Management',
    userId,
    categoryId: SEED_CATEGORIES[4].id,
    imageUrl:
      'https://i.ytimg.com/vi/nz0uEZbnrzs/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDpBTe5zf4JrgyAyMyYQGoOdpNysw',
    price: 50,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Introduction to Management',
    desc: 'Introduction to Management',
    userId,
    categoryId: SEED_CATEGORIES[4].id,
    imageUrl:
      'https://i.ytimg.com/vi/UJS9JrFDuRo/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLA2g46vP1xkHZG4E4MWl-Q0sTh75g',
    price: 80,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
  {
    id: uuidv4(),
    title: 'Operations Management Full Course',
    desc: 'Operations Management Full Course',
    userId,
    categoryId: SEED_CATEGORIES[4].id,
    imageUrl:
      'https://i.ytimg.com/vi/Kt3wUDiUYvw/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBD3UFeKvbocnUBJsIOfFNKfakBzg',
    price: 100,
    isPublished: true,
    level: CourseLevel.ADVANCED,
    date: new Date(),
  },
]
