import { LessonType } from '@/db/schema'
import { v4 as uuidv4 } from 'uuid'

import { SEED_CHAPTERS } from './chapters'
import { SEED_COURSES } from './courses'

export const SEED_LESSONS = [
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[0].id,
    title: `Introduction`,
    description: `Introduction`,
    lessonType: LessonType.VIDEO,
    position: 1,
    isPublished: true,
    isFree: true,
    videoUrl: `https://www.youtube.com/watch?v=TiSGujM22OI`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[0].id,
    title: `Getting Started`,
    description: `Getting Started`,
    lessonType: LessonType.VIDEO,
    position: 2,
    isPublished: true,
    isFree: true,
    videoUrl: `https://www.youtube.com/watch?v=Kt4PQlcLHco`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[1].id,
    title: `Typing Props`,
    description: `Typing Props`,
    lessonType: LessonType.VIDEO,
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=KpA6oEaCHtk`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[1].id,
    title: `Basic Props`,
    description: `Basic Props`,
    lessonType: LessonType.VIDEO,
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=mDu54a5U3OU`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[1].id,
    title: `Advanced Props`,
    description: `Advanced Props`,
    lessonType: LessonType.VIDEO,
    position: 3,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=zLyeWSfTMa8`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[2].id,
    title: `Event Props`,
    description: `Event Props`,
    lessonType: LessonType.VIDEO,
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=xNSIHFi8o2M`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[2].id,
    title: `Style Props`,
    description: `Style Props`,
    lessonType: LessonType.VIDEO,
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=FNfHtujZE4k`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[3].id,
    title: `Prop Types and Tips`,
    description: `Prop Types and Tips`,
    lessonType: LessonType.VIDEO,
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=4Ml7Lp_QcSo`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[3].id,
    title: `useState Hook`,
    description: `useState Hook`,
    lessonType: LessonType.VIDEO,
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=2NKNjeB0WVs`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[3].id,
    title: `useState Future Value`,
    description: `useState Future Value`,
    lessonType: LessonType.VIDEO,
    position: 3,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=LNpWuRUIR5A`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[3].id,
    title: `useState Type Assertion`,
    description: `useState Type Assertion`,
    lessonType: LessonType.VIDEO,
    position: 4,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=U3UizPM4aSk`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[4].id,
    title: `useReducer Hook`,
    description: `useReducer Hook`,
    lessonType: LessonType.VIDEO,
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=lSh9RyYcnPA`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[4].id,
    title: `useReducer Strict Action Types`,
    description: `useReducer Strict Action Types`,
    lessonType: LessonType.VIDEO,
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=bcmes6hUO3U`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[5].id,
    title: `useContext Hook`,
    description: `useContext Hook`,
    lessonType: LessonType.VIDEO,
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=rbtTb9hLYS8`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[5].id,
    title: `useContext Future Value`,
    description: `useContext Future Value`,
    lessonType: LessonType.VIDEO,
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=9726Yq3Scjk`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[6].id,
    title: `useRef Hook`,
    description: `useRef Hook`,
    lessonType: LessonType.VIDEO,
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=hA4i1RTbZ2A`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[6].id,
    title: `Class Component`,
    description: `Class Component`,
    lessonType: LessonType.VIDEO,
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=JOhIMtMxjpU`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[7].id,
    title: `Component Prop`,
    description: `Component Prop`,
    lessonType: LessonType.VIDEO,
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=qvdnTfyv7y8`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[7].id,
    title: `Generic Props`,
    description: `Generic Props`,
    lessonType: LessonType.VIDEO,
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=xFNk2nfDh4M`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[7].id,
    title: `Restricting Props`,
    description: `Restricting Props`,
    lessonType: LessonType.VIDEO,
    position: 3,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=yqn9Fkv7f2M`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[8].id,
    title: `Template Literals and Exclude`,
    description: `Template Literals and Exclude`,
    lessonType: LessonType.VIDEO,
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=jrnIh0RPeCw`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[8].id,
    title: `Wrapping HTML Elements`,
    description: `Wrapping HTML Elements`,
    lessonType: LessonType.VIDEO,
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=4GchlC06ca0`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[8].id,
    title: `Extracting a Component's Prop Types`,
    description: `Extracting a Component's Prop Types`,
    lessonType: LessonType.VIDEO,
    position: 3,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=AHadSDk7i6s`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[8].id,
    title: `Polymorphic Components`,
    description: `Polymorphic Components`,
    lessonType: LessonType.VIDEO,
    position: 4,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=uZ8GZm5KEXY`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[0].id,
    chapterId: SEED_CHAPTERS[9].id,
    title: `Wrapping up`,
    description: `Wrapping up`,
    lessonType: LessonType.VIDEO,
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=YmATkdc-5NY`,
    duration: null,
    question: null,
  },

  // lesson for courses[1]
  {
    id: uuidv4(),
    courseId: SEED_COURSES[1].id,
    chapterId: SEED_CHAPTERS[10].id,
    title: `Introduction & New Features`,
    description: `Introduction & New Features`,
    lessonType: LessonType.VIDEO,
    position: 1,
    isPublished: true,
    isFree: true,
    videoUrl: `https://www.youtube.com/watch?v=TJQbDPGzm0Y`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[1].id,
    chapterId: SEED_CHAPTERS[10].id,
    title: `SSR & Server Components (theory)`,
    description: `SSR & Server Components (theory)`,
    lessonType: LessonType.VIDEO,
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=YEG2_fSJswc`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[1].id,
    chapterId: SEED_CHAPTERS[11].id,
    title: `Pages & Routes`,
    description: `Pages & Routes`,
    lessonType: LessonType.VIDEO,
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=vwg4Wrk-kWE`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[1].id,
    chapterId: SEED_CHAPTERS[11].id,
    title: `Layouts & Links`,
    description: `Layouts & Links`,
    lessonType: LessonType.VIDEO,
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=R7A5vBDfZ18`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[1].id,
    chapterId: SEED_CHAPTERS[12].id,
    title: `Styles, Fonts & Images`,
    description: `Styles, Fonts & Images`,
    lessonType: LessonType.VIDEO,
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=oWUQQD97Rz0`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[1].id,
    chapterId: SEED_CHAPTERS[12].id,
    title: `Fetching & Revalidating Data`,
    description: `Fetching & Revalidating Data`,
    lessonType: LessonType.VIDEO,
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=PAXWRgEo7Ns`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[1].id,
    chapterId: SEED_CHAPTERS[13].id,
    title: `Dynamic Segments (Params)`,
    description: `Dynamic Segments (Params)`,
    lessonType: LessonType.VIDEO,
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=ZwajQ9ywgIU`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[1].id,
    chapterId: SEED_CHAPTERS[13].id,
    title: `Static Rendering`,
    description: `Static Rendering`,
    lessonType: LessonType.VIDEO,
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=ihmyC4Ei2zY`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[1].id,
    chapterId: SEED_CHAPTERS[13].id,
    title: `Custom 404 Page`,
    description: `Custom 404 Page`,
    lessonType: LessonType.VIDEO,
    position: 3,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=PbFH_VE1Iks`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[1].id,
    chapterId: SEED_CHAPTERS[14].id,
    title: `Loading UI & Suspense`,
    description: `Loading UI & Suspense`,
    lessonType: LessonType.VIDEO,
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=Lzml9L3f4IM`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[1].id,
    chapterId: SEED_CHAPTERS[14].id,
    title: `Client Form Component`,
    description: `Client Form Component`,
    lessonType: LessonType.VIDEO,
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=nSfu7sHPE9M`,
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[1].id,
    chapterId: SEED_CHAPTERS[15].id,
    title: `Building the App`,
    description: `Building the App`,
    lessonType: LessonType.VIDEO,
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: `https://www.youtube.com/watch?v=Yi_zS8jSln8`,
    duration: null,
    question: null,
  },

  // lesons for courses[2]
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[16].id,
    title: 'Introduction',
    description: 'Introduction',
    lessonType: 'VIDEO',
    position: 1,
    isPublished: true,
    isFree: true,
    videoUrl: 'https://www.youtube.com/watch?v=ZjAqacIC_3c',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[16].id,
    title: 'Hello World',
    description: 'Hello World',
    lessonType: 'VIDEO',
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=kVddMV-TrSw',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[16].id,
    title: 'Project Structure',
    description: 'Project Structure',
    lessonType: 'VIDEO',
    position: 3,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=FmerxXWD66g',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[16].id,
    title: 'Before We Start',
    description: 'Before We Start',
    lessonType: 'VIDEO',
    position: 4,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=x7oQC_R_yVo',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[17].id,
    title: 'Routing',
    description: 'Routing',
    lessonType: 'VIDEO',
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=Vm7qM1wmXwE',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[17].id,
    title: 'Nested Routes',
    description: 'Nested Routes',
    lessonType: 'VIDEO',
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=mEral6yz130',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[17].id,
    title: 'Dynamic Routes',
    description: 'Dynamic Routes',
    lessonType: 'VIDEO',
    position: 3,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=N4-EkNJ6RFM',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[17].id,
    title: 'Nested Dynamic Routes',
    description: 'Nested Dynamic Routes',
    lessonType: 'VIDEO',
    position: 4,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=Vn4p4K6_M44',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[17].id,
    title: 'Catch all Segments',
    description: 'Catch all Segments',
    lessonType: 'VIDEO',
    position: 5,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=Ssw6-69KLRo',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[17].id,
    title: 'Not Found Page',
    description: 'Not Found Page',
    lessonType: 'VIDEO',
    position: 6,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=tW3rVL7xc8Y',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[17].id,
    title: 'File Colocation',
    description: 'File Colocation',
    lessonType: 'VIDEO',
    position: 7,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=kO2nTCgcJLc',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[17].id,
    title: 'Private Folders',
    description: 'Private Folders',
    lessonType: 'VIDEO',
    position: 8,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=nQKtuiccMLs',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[17].id,
    title: 'Route Groups',
    description: 'Route Groups',
    lessonType: 'VIDEO',
    position: 93,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=Tpo5wBuk3po',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[17].id,
    title: 'Layouts',
    description: 'Layouts',
    lessonType: 'VIDEO',
    position: 10,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=f93g238p9tM',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[17].id,
    title: 'Nested Layouts',
    description: 'Nested Layouts',
    lessonType: 'VIDEO',
    position: 11,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=FWlUf4FEQ1M',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[17].id,
    title: 'Route Group Layout',
    description: 'Route Group Layout',
    lessonType: 'VIDEO',
    position: 12,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=V5GKwuzKQV0',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[17].id,
    title: 'Routing Metadata',
    description: 'Routing Metadata',
    lessonType: 'VIDEO',
    position: 13,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=yE_y4EBq-EA',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[17].id,
    title: 'title Metadata',
    description: 'title Metadata',
    lessonType: 'VIDEO',
    position: 14,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=1OqftoKO2V0',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[17].id,
    title: 'Link Component Navigation',
    description: 'Link Component Navigation',
    lessonType: 'VIDEO',
    position: 15,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=TVAF5Fr_2QA',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[17].id,
    title: 'Active Links',
    description: 'Active Links',
    lessonType: 'VIDEO',
    position: 16,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=jzD1mUd35a0',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[17].id,
    title: 'Navigating Programmatically',
    description: 'Navigating Programmatically',
    lessonType: 'VIDEO',
    position: 17,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=7jBHW98vNjw',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[18].id,
    title: 'Templates',
    description: 'Templates',
    lessonType: 'VIDEO',
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=7xVWvL-37EE',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[18].id,
    title: 'Loading UI',
    description: 'Loading UI',
    lessonType: 'VIDEO',
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=PrxdiJrrrWs',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[18].id,
    title: 'Error Handling',
    description: 'Error Handling',
    lessonType: 'VIDEO',
    position: 3,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=UcnCZ0lXZbo',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[18].id,
    title: 'Recovering from Errors',
    description: 'Recovering from Errors',
    lessonType: 'VIDEO',
    position: 4,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=f7LqNoMAAUc',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[18].id,
    title: 'Handling Errors in Nested Routes',
    description: 'Handling Errors in Nested Routes',
    lessonType: 'VIDEO',
    position: 5,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=YG98I2Bj7qw',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[18].id,
    title: 'Handling Errors in Layouts',
    description: 'Handling Errors in Layouts',
    lessonType: 'VIDEO',
    position: 6,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=3V6ho699MDg',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[19].id,
    title: 'Parallel Routes',
    description: 'Parallel Routes',
    lessonType: 'VIDEO',
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=8I5-OTNOni0',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[19].id,
    title: 'Unmatched Routes',
    description: 'Unmatched Routes',
    lessonType: 'VIDEO',
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=NPtnJ6Ivv9k',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[19].id,
    title: 'Conditional Routes',
    description: 'Conditional Routes',
    lessonType: 'VIDEO',
    position: 3,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=7HrOjvKIfRs',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[19].id,
    title: 'Intercepting Routes',
    description: 'Intercepting Routes',
    lessonType: 'VIDEO',
    position: 4,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=nr_kRfTJfKc',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[19].id,
    title: 'Parallel Intercepting Routes',
    description: 'Parallel Intercepting Routes',
    lessonType: 'VIDEO',
    position: 5,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=mVOvx9eVHg0',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[19].id,
    title: 'Route Handlers',
    description: 'Route Handlers',
    lessonType: 'VIDEO',
    position: 6,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=25yY2RVRq_M',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[19].id,
    title: 'Handling GET Request',
    description: 'Handling GET Request',
    lessonType: 'VIDEO',
    position: 7,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=b3ue9WL5fk8',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[19].id,
    title: 'Handling POST Request',
    description: 'Handling POST Request',
    lessonType: 'VIDEO',
    position: 8,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=pzPS7Fn-8tE',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[19].id,
    title: 'Dynamic Route Handlers',
    description: 'Dynamic Route Handlers',
    lessonType: 'VIDEO',
    position: 9,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=TGbC8F0gjC8',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[19].id,
    title: 'Handling PATCH Request',
    description: 'Handling PATCH Request',
    lessonType: 'VIDEO',
    position: 10,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=bDbBh7lEamE',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[19].id,
    title: 'Handling DELETE Request',
    description: 'Handling DELETE Request',
    lessonType: 'VIDEO',
    position: 11,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=x3KCt1Oc278',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[19].id,
    title: 'URL Query Parameters',
    description: 'URL Query Parameters',
    lessonType: 'VIDEO',
    position: 12,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=fuxSl-K0oI0',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[19].id,
    title: 'Redirects in Route Handlers',
    description: 'Redirects in Route Handlers',
    lessonType: 'VIDEO',
    position: 13,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=54eKbXPrvuo',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[19].id,
    title: 'Headers in Route Handlers',
    description: 'Headers in Route Handlers',
    lessonType: 'VIDEO',
    position: 14,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=pxHbFrahyLY',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[19].id,
    title: 'Cookies in Route Handlers',
    description: 'Cookies in Route Handlers',
    lessonType: 'VIDEO',
    position: 15,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=1qd3_OGL5Ko',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[19].id,
    title: 'Caching in Route Handlers',
    description: 'Caching in Route Handlers',
    lessonType: 'VIDEO',
    position: 16,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=5_cJFYZSiDM',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[19].id,
    title: 'Middleware',
    description: 'Middleware',
    lessonType: 'VIDEO',
    position: 17,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=xrvul-JrKFI',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[20].id,
    title: 'Rendering',
    description: 'Rendering',
    lessonType: 'VIDEO',
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=fjLXVGDqix0',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[20].id,
    title: 'Client-side Rendering (CSR)',
    description: 'Client-side Rendering (CSR)',
    lessonType: 'VIDEO',
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=OXrNQPhzH84',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[20].id,
    title: 'Server-side Rendering (SSR)',
    description: 'Server-side Rendering (SSR)',
    lessonType: 'VIDEO',
    position: 3,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=3e017ih7pOA',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[20].id,
    title: 'Suspense for SSR',
    description: 'Suspense for SSR',
    lessonType: 'VIDEO',
    position: 4,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=NdSthd1Ek8Q',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[20].id,
    title: 'React Server Components (RSC)',
    description: 'React Server Components (RSC)',
    lessonType: 'VIDEO',
    position: 5,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=5h-e5hNKx-c',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[20].id,
    title: 'Server and Client Components',
    description: 'Server and Client Components',
    lessonType: 'VIDEO',
    position: 6,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=KvjWqn1VpPc',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[20].id,
    title: 'RSC Rendering Lifecycle',
    description: 'RSC Rendering Lifecycle',
    lessonType: 'VIDEO',
    position: 7,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=o57paErp8Pc',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[20].id,
    title: 'Static Rendering',
    description: 'Static Rendering',
    lessonType: 'VIDEO',
    position: 8,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=WCcqnFRF9YA',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[20].id,
    title: 'Dynamic Rendering',
    description: 'Dynamic Rendering',
    lessonType: 'VIDEO',
    position: 9,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=-7Rrjy-lfcE',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[20].id,
    title: 'Streaming',
    description: 'Streaming',
    lessonType: 'VIDEO',
    position: 10,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=9REGGiU8hck',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[20].id,
    title: 'Server and Client Composition Patterns',
    description: 'Server and Client Composition Patterns',
    lessonType: 'VIDEO',
    position: 11,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=7bsYcb3nWYA',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[20].id,
    title: 'Server-only Code',
    description: 'Server-only Code',
    lessonType: 'VIDEO',
    position: 12,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=t2tNpubt4y0',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[20].id,
    title: 'Third Party Packages',
    description: 'Third Party Packages',
    lessonType: 'VIDEO',
    position: 13,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=I4w5uZzdT1A',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[20].id,
    title: 'Context Providers',
    description: 'Context Providers',
    lessonType: 'VIDEO',
    position: 14,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=Ou2IAs7W1Ig',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[20].id,
    title: 'Client-only Code',
    description: 'Client-only Code',
    lessonType: 'VIDEO',
    position: 15,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=xn1LpTw-pzc',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[20].id,
    title: 'Client Component Placement',
    description: 'Client Component Placement',
    lessonType: 'VIDEO',
    position: 16,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=MdpoBLCDmJo',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[20].id,
    title: 'Interleaving Server and Client Components',
    description: 'Interleaving Server and Client Components',
    lessonType: 'VIDEO',
    position: 17,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=-RRiLnKSj8k',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[21].id,
    title: 'Data Fetching',
    description: 'Data Fetching',
    lessonType: 'VIDEO',
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=gBLro0UcwKw',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[21].id,
    title: 'Fetching Data with Server Components',
    description: 'Fetching Data with Server Components',
    lessonType: 'VIDEO',
    position: 2,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=WAm-T04ztrs',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[21].id,
    title: 'Loading and Error States',
    description: 'Loading and Error States',
    lessonType: 'VIDEO',
    position: 3,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=Or2aZfITRpU',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[21].id,
    title: 'JSON Server Setup',
    description: 'JSON Server Setup',
    lessonType: 'VIDEO',
    position: 4,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=bG6boMwCvk4',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[21].id,
    title: 'Caching Data',
    description: 'Caching Data',
    lessonType: 'VIDEO',
    position: 5,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=6rRHJZAAV1E',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[21].id,
    title: 'Data Cache',
    description: 'Data Cache',
    lessonType: 'VIDEO',
    position: 6,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=_sIug3Y1YcA',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[21].id,
    title: 'Opting Out of Caching',
    description: 'Opting Out of Caching',
    lessonType: 'VIDEO',
    position: 7,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=PlgDOhWFOno',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[21].id,
    title: 'Request Memoization',
    description: 'Request Memoization',
    lessonType: 'VIDEO',
    position: 8,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=tcLe3Xi0fJE',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[21].id,
    title: 'Time based Data Revalidation',
    description: 'Time based Data Revalidation',
    lessonType: 'VIDEO',
    position: 9,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=dR0diq3EvDE',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[21].id,
    title: 'Client-side Data Fetching',
    description: 'Client-side Data Fetching',
    lessonType: 'VIDEO',
    position: 10,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=zfaDdKH5Zv8',
    duration: null,
    question: null,
  },
  {
    id: uuidv4(),
    courseId: SEED_COURSES[2].id,
    chapterId: SEED_CHAPTERS[22].id,
    title: 'Next.js 15 is FINALLY here!',
    description: 'Next.js 15 is FINALLY here!',
    lessonType: 'VIDEO',
    position: 1,
    isPublished: true,
    isFree: false,
    videoUrl: 'https://www.youtube.com/watch?v=RxSAUaAkHxA',
    duration: null,
    question: null,
  },
]
